### ISSUE TITLE
OneToMany relation doesn't save

### ISSUE THREAD

**Issue by Asyjjan** [knpuniversity/easyadminbundle#2]
Hi, i'm working with symfony 5 and easyadmin 3 and i've read I think every doc about doctrine and issues with my problem but none of them solved my problem.

I have an Gif entity that contains several images (which is also an entity), and I have an Exercice entity where I would like to be able to select those Gif so it's an One To Many relation (each exercice can have multiple gif but a gif is used in only one exercice), when I create the property in each entity with bin/console make:entity, and then update my database, everything is alright but when I try to create an Exercice, it doesn't save the Gif in the Exercice that has been created, I can share my code with you hopping someone can help me :

and then I display the field like this in my Exercice crud controller :

Thanks for those who will help me :)

**Comment by oxyopu** [comment]
You need to associate entities in the crud entity where there is an "entity_id" in your database, otherwise it won't work

**Comment by MolloKhan** [comment]
Hi! I'll have to close this ticket because this is not related to our EasyAdminBundle 1 tutorial, which by the way, we're working on a tutorial for version 3.

@Asyjjan if you have more questions feel free to leave us a message in the comments of the tutorial or you can also raise a ticket directly on the EasyAdminBundle Github project
